services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productos_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./Backend/Partial
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./Front
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge